### ISSUE TITLE
Didn't work with the current cura version

### ISSUE THREAD

**Issue by BerndJM** [markwal/Cura-OctoPrintUpload#1]
Hi Mark,
first, I'm happy to see that you still work on that plugin.
It's exactly the plugin for my workflow (I used for long time with Cura 14.xx):
Slicing with cura - sending to one of my octoprint(ers). Nothing more, nothing less ;-))
The Cura's octoprint-plugin is much too much. I don't like to monitor the print via Cura and so on...
But now to the problem:
Your plugin works so far with Cura 2.3.1 (under Ubuntu) - I can configure my printers and the entries in the save select appear "save to octo..." -  'til the moment I want to send a file. the following error occurrs:

2016-11-07 21:28:21,535 - ERROR - .../UM/Logger.py (logException [53]): Exception: Job <UM.Mesh.WriteMeshJob.WriteMeshJob object at 0x7f47dbd182b0> caused an exception
2016-11-07 21:28:21,587 - ERROR - .../UM/Logger.py (logException [53]): Traceback (most recent call last):
2016-11-07 21:28:21,588 - ERROR - .../UM/Logger.py (logException [53]):   File "/usr/lib/python3/dist-packages/UM/JobQueue.py", line 122, in run
2016-11-07 21:28:21,588 - ERROR - .../UM/Logger.py (logException [53]):     job.run()
2016-11-07 21:28:21,591 - ERROR - .../UM/Logger.py (logException [53]):   File "/usr/lib/python3/dist-packages/UM/Mesh/WriteMeshJob.py", line 37, in run
2016-11-07 21:28:21,592 - ERROR - .../UM/Logger.py (logException [53]):     self.setResult(self._writer.write(self._stream, self._nodes, self._mode))
2016-11-07 21:28:21,593 - ERROR - .../UM/Logger.py (logException [53]):   File "/usr/lib/cura/plugins/GCodeWriter/GCodeWriter.py", line 59, in write
2016-11-07 21:28:21,594 - ERROR - .../UM/Logger.py (logException [53]):     stream.write(gcode)
2016-11-07 21:28:21,595 - ERROR - .../UM/Logger.py (logException [53]): TypeError: write(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str'

Unfortunately I'm not a Python programmer but I would very much appreciate if you would be able to fix this issue. Can I provide further information?

Best regards Bernd

**Comment by markwal** [comment]
Yeah.  I noticed they changed something between beta and release.  I haven't looked into it yet.  Perhaps soon.

**Comment by gretel** [comment]
i feel lucky using `Cura 2.4.0-BETA2` on a mac.

**Comment by markwal** [comment]
Latest version of the plugin (0 2) should work with 2.3.1 on all OSes hopefully.  2.4.0 beta I haven't tested yet.

**Comment by BerndJM** [comment]
Hey Mark - you made my day :-))

Can confirm that it also works in the 2.4Beta (from PPA) on Ubuntu 16.04

And for your Readme - this is the Installationpath for (Ubuntu)Linux:
`/home/[YOUR_USERNAME]/.local/share/cura/plugins/Cura-OctoPrintUpload`

**Comment by markwal** [comment]
Appears to work with 2.5.0 as well
