### ISSUE TITLE
Doesn't work in Cura 2.3.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by burbilog** [markwal/Cura-OctoPrintUpload#2]
If I choose Extensions->Octoprint->Octoprint servers nothing happens and following lines appear in log file:

```2016-12-08 00:43:46,191 - CRITICAL - .../cura/CrashHandler.py (show [24]): An uncaught exception has occurred!
2016-12-08 00:43:46,192 - CRITICAL - .../cura/CrashHandler.py (show [24]): Traceback (most recent call last):
2016-12-08 00:43:46,193 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/opt/cura/lib/python3/dist-packages/UM/Qt/Bindings/ExtensionModel.py", line 47, in subMenuTriggered
2016-12-08 00:43:46,194 - CRITICAL - .../cura/CrashHandler.py (show [24]):     item["extension"].activateMenuItem(option_name)
2016-12-08 00:43:46,195 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/opt/cura/lib/python3/dist-packages/UM/Extension.py", line 36, in activateMenuItem
2016-12-08 00:43:46,195 - CRITICAL - .../cura/CrashHandler.py (show [24]):     self._menu_function_dict[name]()
2016-12-08 00:43:46,196 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/home/rm/.local/share/cura/plugins/Cura-OctoPrintUpload/OctoPrintPlugin.py", line 61, in showSettingsDialog
2016-12-08 00:43:46,197 - CRITICAL - .../cura/CrashHandler.py (show [24]):     self._showDialog("OctoPrintPlugin.qml")
2016-12-08 00:43:46,198 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/home/rm/.local/share/cura/plugins/Cura-OctoPrintUpload/OctoPrintPlugin.py", line 57, in _showDialog
2016-12-08 00:43:46,199 - CRITICAL - .../cura/CrashHandler.py (show [24]):     self._dialogs[qml] = self._createDialog(qml)
2016-12-08 00:43:46,200 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/home/rm/.local/share/cura/plugins/Cura-OctoPrintUpload/OctoPrintPlugin.py", line 44, in _createDialog
2016-12-08 00:43:46,200 - CRITICAL - .../cura/CrashHandler.py (show [24]):     path = QUrl.fromLocalFile(os.path.join(PluginRegistry.getInstance().getPluginPath("OctoPrintOutputDevice"), qml))
2016-12-08 00:43:46,201 - CRITICAL - .../cura/CrashHandler.py (show [24]):   File "/usr/local/lib/python3.4/posixpath.py", line 82, in join
2016-12-08 00:43:46,201 - CRITICAL - .../cura/CrashHandler.py (show [24]):     path += b
2016-12-08 00:43:46,202 - CRITICAL - .../cura/CrashHandler.py (show [24]): TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

Please, don't give up working on this plugin! It would be great to be able to send prints to octoprint!

**Comment by markwal** [comment]
I haven't given up on it, but don't have time to look at it again for a couple of weeks.  I noticed that they broke compatibility before they released Cura 2.3.1 so while it was working on a pre-release build, it doesn't work anymore.  I imagine I'll have it fixed by the end of the month though.

**Comment by cmock** [comment]
It seems that the plugin sub-directory must be named like the plugin; that is, renaming `~/.local/share/cura/plugins/Cura-OctoPrintUpload` to `.../OctoPrintOutputDevice` made it work for me.

Thanks for this very useful plugin!

**Comment by markwal** [comment]
Should work now.
